title: S.L.O.P. Case Files
description: "A dark, edgy dive into AI dysfunction and digital decay."
baseurl: ""
url: "https://your-production-url.com"
markdown: kramdown
theme: jekyll-theme-minimal
sass:
  sass_dir: assets/css
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# Build settings
highlighter: rouge

# GitHub Pages defaults
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 